export const ActionsTypes = {
    SET_PEOPLE: 'SET_PEOPLE',
    SELECTED_PEOPLE: 'SELECTED_PEOPLE',
    FILTER_PEOPLE: 'FILTER_PEOPLE',
    DELETE_PEOPLE: 'DELETE_PEOPLE',
    CLEAN_FILTER: 'CLEAN_FILTER',
};
